### ISSUE TITLE
Title of the documentation

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#14]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/dae433e875ec27d911571ae69f80323ce806baea/index.html#L7

If you want to customize this, you probably should. That's a low-hanging-fruit. And since this is static it would even help your SEO score too.

**Comment by agisulyok** [comment]
corrected
