### ISSUE TITLE
Links and buttons

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#15]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/dae433e875ec27d911571ae69f80323ce806baea/src/components/LandingPage.jsx#L20-L21

Usually we do not put links into buttons, it might misbehave in different environments (browsers/operating systems/screen readers) differently.

My best guess is that you needed this for styling purposes, which should be achieved by styling rather than semantically.

On the other hand the whole page is looking good in terms of semantic HTML point of view.
(p.s.: some formatting wouldn't hurt tho)

**Comment by agisulyok** [comment]
corrected
