### ISSUE TITLE
Vitest plugins

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#16]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/dae433e875ec27d911571ae69f80323ce806baea/vitest.config.js#L3-L4

You probably import `React` itself at the top of your components because some tests did not know what things are. If you add the `react()` plugin here too, you do not need to import react everywhere.

**Comment by agisulyok** [comment]
corrected
