### ISSUE TITLE
Classes and id as css selectors which are identical with html tags

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#17]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/dae433e875ec27d911571ae69f80323ce806baea/src/components/LandingPage.jsx#L9

(Opinion) I would not use css classes and/or object, which are same as a html tag, it will be easy to confuse and it is not really bringing any benefits.

**Comment by agisulyok** [comment]
corrected
