### ISSUE TITLE
empty string versus undefined vs null

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#18]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/dae433e875ec27d911571ae69f80323ce806baea/src/components/LoginForm.jsx#L28

Just to be clear using empty strings here works. But I would rather use null or undefined, since those have different meanings.

**Comment by agisulyok** [comment]
corrected
