### ISSUE TITLE
br tag for styling is not a good practice

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#19]
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/dae433e875ec27d911571ae69f80323ce806baea/src/components/RegistrationForm.jsx#L39

The visual modifications should be - most of the times - achieved by css styling rather than adding another tag. Please try to avoid using `<br/>` tags for styling. 

Hint: you pretty much can use https://www.w3schools.com/css/css3_flexbox.asp instead.

**Comment by agisulyok** [comment]
noted, corrected
