### ISSUE TITLE
Refactor to displayName

### ISSUE THREAD

**Issue by bsnAndras** [gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main#32]
The backend now uses displayName instead of username. We should rename every occurence to match.

e.g.:
https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/blob/375f6075931a305f60ce11ed49160070ae33367d/src/components/RegistrationForm.jsx#L11

**Comment by AIRewan** [comment]
changed in [visual-patches] https://github.com/gfa-cc-after/StudyGroup_1_PET_Clinic_Frontend-main/tree/visual-patches

**Comment by agisulyok** [comment]
I close the issue, this will be resolved after merging above branch
